version: v1
name: "bigquery"
type: depot
tags:
  - bigquery
layer: user
depot:
  type: BIGQUERY
  description: "Google Cloud BigQuery"
  spec:
    project: dataos-ck-res-yak-dev
  external: true
  connectionSecret:
    - acl: rw
      type: key-value-properties
      files:
        json_keyfile: ./secrets/gcp-demo-sa.json