---
name: "customer-data-product"
version: v1beta
type: bundle
tags:
  - customer
description: This bundle resource is for customer data product.
layer: "user"
bundle:
  workspaces:
    - name: customer
      description: "This workspace runs dataos bundle resource for demo"
      tags:
        - customer
      labels:
        "name" : "customer"
      layer: "user"
  resources:
    - id: dp-customer-depot
      file: input/config-bigquery-depot.yaml
      workspace: customer

      
    - id: customer-ingestion-pipeline
      file: dag/config-customer-pipeline.yaml
      workspace: customer
      dependencies:
        - dp-customer-depot



