version: v1
name: wf-customer-dp-pipline
type: workflow
tags:
  - demo.customer
description: The job ingests customer data from Blob Storage to icebase.
workflow:
  title: Customer Data Product Pipeline
  dag:
    - name: ingest-customer-data    
      file: transformation/config-customer-overview.yaml
      retry:
        count: 2
        strategy: "Always"
    

    - name: data-tool-customer
      file: output/set-meta-data/config-customer-latest-version.yaml
      dependencies:
        - ingest-customer-data   
      retry:
        count: 2
        strategy: "Always"

    - name: profile-customer-data
      file: output/profile/config-customer-profile.yaml
      dependencies:
        - data-tool-customer
      retry:
        count: 2
        strategy: "Always"


    - name: quality-customer-data
      file: output/assertions/config-customer-quality.yaml
      dependencies:
        -  profile-customer-data
      retry:
        count: 2
        strategy: "Always"

